page_cache_query_ignore.settings:
  type: config_object
  label: 'Page cache query parameters ignore config'
  mapping:
    ignored_parameters:
      type: sequence
      label: 'Ignored parameters'
      sequence:
        type: string
        label: 'Ignored param'
